-- 전체 조회
SELECT * FROM ANIMAL_INS;

-- 최댓값 구하기
SELECT MAX(DATETIME)
FROM ANIMAL_INS;

-- 최솟값 구하기
SELECT MIN(DATETIME)
FROM ANIMAL_INS;

-- 동물 수 구하기
SELECT COUNT(ANIMAL_ID)
FROM ANIMAL_INS;

-- 중복 제거하기
SELECT COUNT(DISTINCT NAME)
FROM ANIMAL_INS;

-- 타입별 동물 수 구하기
SELECT ANIMAL_TYPE, COUNT(*) count
FROM ANIMAL_INS
GROUP BY ANIMAL_TYPE
ORDER BY ANIMAL_TYPE;

-- 동명 동물 수 찾기
SELECT NAME, COUNT(NAME)
FROM ANIMAL_INS
GROUP BY NAME
HAVING COUNT(NAME)>=2
ORDER BY NAME;

-- 입양 시각 구하기(1)
SELECT HOUR(DATETIME) HOUR, COUNT(HOUR(DATETIME))
FROM ANIMAL_OUTS
GROUP BY HOUR(DATETIME)
HAVING HOUR>=9 AND HOUR<=19
ORDER BY HOUR(DATETIME);