# 오랜 기간 보호한 동물(2)
SELECT ANIMAL_INS.ANIMAL_ID, ANIMAL_INS.NAME
FROM ANIMAL_INS
    LEFT JOIN ANIMAL_OUTS ON ANIMAL_INS.ANIMAL_ID = ANIMAL_OUTS.ANIMAL_ID
WHERE ANIMAL_OUTS.DATETIME IS NOT NULL
ORDER BY ANIMAL_OUTS.DATETIME-ANIMAL_INS.DATETIME DESC
LIMIT 2;